// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evxmwcluivveyvbksehw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2eG13Y2x1aXZ2ZXl2YmtzZWh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NzU4OTUsImV4cCI6MjA3MjA1MTg5NX0.OH0Gq1jEF1BIJDfNCP0tGpRbrSNPK3sPwnB9oxIqqps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});